from turtle import *
def rset():
    pensize(1)
    pencolor('black')
    penup()
    home()
    pendown()
def offset(off_set, angle=0, mode='taiji'):
    penup()
    home()  
    if mode == 'taiji': 
        right(90)
        fd(off_set)
        seth(0)  
    else:  
        left(angle)  
        fd(off_set)
        left(90)
    pendown()
def taiji(radius, pen_size=2, color='black'):
    rset()  
    pensize(pen_size)
    pencolor(color)
    offset(radius)  
    fillcolor('black')  
    begin_fill()  
    circle(radius, 180)  
    circle(radius / 2, 180) 
    circle(-radius / 2, 180) 
    end_fill() 
    circle(-radius, 180)  
    begin_fill()
    fillcolor('white')
    penup()
    home()  
    left(90)
    fd(radius * 0.7)  
    right(90)
    pendown()
    circle(-radius * 0.2)  
    end_fill()
    rset()
    penup()
    begin_fill()
    fillcolor('black')
    right(90)
    fd(radius * 0.7)
    left(90)
    pendown()
    circle(radius * 0.2)
    end_fill()
def bagua(off_set, side, gua_lis):
    pensize(side / 2)
    for j, k in enumerate(gua_lis):  
        angl = j * 45  
        rset()  
        offset(off_set, angle=angl, mode='bagua') 
        pencolor('white')
        pensize(5)
        bk(side / 2)
        for i in k: 
            pencolor('black')
            if i == 1:
                fd(side)
            elif i == 0:
                fd(side * (1 / 3))
                penup()
                fd(side * (1 / 3))
                pendown()
                fd(side * (1 / 3))
            elif isinstance(i, str) and j <= 4:  
                penup()
                fd(side / 2)
                pendown()
                write(i, align='center', font=('楷体', 15, "bold"))  
            else: 
                penup()
                fd(side / 2)
                right(90)
                fd(15)
                pendown()
                write(i, align='center', font=('楷体', 15, "bold"))
            penup()  
            bk(side / 2)
            right(90)
            fd(side / 2)
            left(90)
            bk(side / 2)
            pendown()
gua_lis = [(1, 1, 0, '兑'), (0, 0, 0, '坤'), (1, 0, 1, '离'), (0, 1, 1, '巽'), (1, 0, 0, '震'), (0, 0, 1, '艮'),
           (0, 1, 0, '坎'), (1, 1, 1, '乾')]
taiji(50)
bagua(70, 30, gua_lis)
hideturtle()
done()
